services:
  malaideu:
    image: ghcr.io/pratikbhattarai76/malaideu:latest
    container_name: malaideu
    restart: unless-stopped
    env_file:
      - ./app/src/.env
    ports:
      - "3000:3000"
