- name: Prepare deployment folder for file upload app
  hosts: aws
  become: true

  vars:
    app_name: aws-file-upload
    base_path: /home/ubuntu/docker
    app_path: "{{ base_path }}/{{ app_name }}"

  tasks:
    - name: Ensure base docker directory exists
      file:
        path: "{{ base_path }}"
        state: directory
        owner: ubuntu
        group: ubuntu
        mode: "0755"

    - name: Ensure app directory exists
      file:
        path: "{{ app_path }}"
        state: directory
        owner: ubuntu
        group: ubuntu
        mode: "0755"

    - name: Copy docker-compose.yml
      copy:
        src: ../docker/docker-compose.yml
        dest: "{{ app_path }}/docker-compose.yml"
        owner: ubuntu
        group: ubuntu
        mode: "0644"

    - name: Copy .env file
      copy:
        src: ../app/src/.env
        dest: "{{ app_path }}/app/.env"
        owner: ubuntu
        group: ubuntu
        mode: "0600"
